ln -s `pwd`/.vim "$HOME/.vim"
ln -s `pwd`/.tmux.conf "$HOME/.tmux.conf"
ln -s `pwd`/.bashrc "$HOME/.bashrc"
ln -s `pwd`/.bash_aliases "$HOME/.bash_aliases"
ln -s `pwd`/.Xmodmap "$HOME/.Xmodmap"
ln -s `pwd`/.inputrc "$HOME/.inputrc"
