runtime vundles.vim
runtime gitconfig.vim
runtime rubyconfig.vim
runtime jsconfig.vim

filetype indent on
syntax enable
colorscheme Monokai
set backspace=indent,eol,start
set ignorecase
set smartcase
set hlsearch
set incsearch
highlight Normal ctermbg=none
highlight NonText ctermbg=none
set laststatus=2
let g:airline_powerline_fonts=1
set smartindent
set autoindent
set expandtab
set tabstop=2
set softtabstop=2
set shiftwidth=2
set rnu
set nu
set fdm=syntax
set breakindent
set linebreak
set showbreak=↪\ 

let mapleader = "\\"
map <space> :
map <CR> <Leader>
inoremap jk <Esc>
