runtime vundles.vim
runtime gitconfig.vim
runtime rubyconfig.vim
runtime jsconfig.vim
runtime airlineconfig.vim

filetype indent on
syntax enable
set background=dark
colorscheme solarized
set backspace=indent,eol,start
set ignorecase
set smartcase
set hlsearch
set incsearch
highlight Normal ctermbg=none
highlight NonText ctermbg=none
set smartindent
set autoindent
set expandtab
set tabstop=2
set softtabstop=2
set shiftwidth=2
set rnu
set nu
set fdm=syntax
set breakindent
set linebreak
set showbreak=↪\ 
set hidden

" swap files (.swp) in a common location
" // means use the file's full path
set dir=~/.vim/_swap//

" backup files (~) in a common location if possible
set backup
set backupdir=~/.vim/_backup/,~/tmp,.

" turn on undo files, put them in a common location
set undofile
set undodir=~/.vim/_undo/

autocmd BufRead,BufNewFile *.css,*.scss,*.less setlocal foldmethod=marker foldmarker={,}
autocmd FileType slim,stylus,jade setlocal foldmethod=indent

let mapleader = "\\"
map <space> :
map <CR> <Leader>
inoremap jk <Esc>
nnoremap <Tab> gt
nnoremap <S-Tab> gT
nnoremap <C-t> :tabe .<CR>
inoremap <CR> <CR>x<BS>
nnoremap o ox<BS>
nnoremap O Ox<BS>
